### PR TITLE
Adding ability to set description on check

### PR DESCRIPTION
**Pull request by icaho**

### CODE REVIEW

**Comment by kristofferahl** [comment]
Thanks for the PR @icaho! Will be looking to merge this and the other PRs as soon as possible but having a really busy week.

**Comment by kristofferahl** [comment]
Maybe @masutaka can help test and merge?

**Comment by masutaka** [comment]
I'm sorry, but it's difficult to do. In fact, I moved to another project a while ago and I don't use healthchecks.io nowadays. :bow:

**Comment by icaho** [comment]
Well I probably shouldn't peer review my own changes but happy to help in future with reviews/contributions.
We are currently using my patched version in our org, so it does work for us. Here's hoping you can look at it soon 😁

**Review by kristofferahl — APPROVED** [review]
Looks good to me!

**Comment by kristofferahl** [comment]
@icaho Sorry for the delay! If you're interested in helping out, it would be great. 😄

**Pull request merged**
